# Generated by Django 3.2.12 on 2025-07-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_client_type_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facial_recognition',
            field=models.BooleanField(default=False, verbose_name='facial recognition'),
        ),
    ]
