# Generated by Django 3.0 on 2021-07-21 17:44

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationNews',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción de la clasificacion de novedad', max_length=255, unique=True, verbose_name='description')),
                ('priority', models.CharField(help_text='Prioridad de la clasificacion de novedad', max_length=255, verbose_name='priority')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(help_text='Código del material', max_length=255, unique=True, verbose_name='code')),
                ('serial', models.CharField(help_text='Serial del material', max_length=255, unique=True, verbose_name='serial')),
                ('description', models.CharField(help_text='Descripción del material', max_length=255, unique=True, verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialNews',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Material', verbose_name='material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('message', models.TextField(help_text='Mensaje de la novedad', verbose_name='message')),
                ('info', jsonfield.fields.JSONField(default=dict)),
                ('employee', models.CharField(help_text='Ficha del trabajador que generó la novedad', max_length=255, verbose_name='employee')),
                ('created_by', models.ForeignKey(help_text='Creado por', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('materials', models.ManyToManyField(related_name='materials', through='core.MaterialNews', to='core.Material', verbose_name='materials')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(help_text='Código de la persona', max_length=255, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Nombre de la persona', max_length=255, verbose_name='name')),
                ('lastname', models.CharField(help_text='Apellido de la persona', max_length=255, verbose_name='lastname')),
                ('doc_ident', models.CharField(help_text='Dpcumento de Identidad de la persona', max_length=255, unique=True, verbose_name='doc_ident')),
                ('address', models.CharField(help_text='Dirección de la persona', max_length=255, verbose_name='address')),
                ('phone', models.CharField(help_text='Teléfono de la persona', max_length=255, verbose_name='phone')),
                ('mobile', models.CharField(help_text='Número de celular de la persona', max_length=255, verbose_name='mobile')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción del horario', max_length=255, unique=True, verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción del Tipo de Persona', max_length=255, unique=True, verbose_name='code')),
                ('priority', models.CharField(help_text='Prioridad del tipo de persona', max_length=255, verbose_name='code')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('license_plate', models.CharField(help_text='Placa del vehiculo', max_length=255, unique=True, verbose_name='license_plate')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleNews',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.News', verbose_name='news')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Vehicle', verbose_name='vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeNews',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción del tipo de novedad', max_length=255, unique=True, verbose_name='description')),
                ('template', models.CharField(help_text='Plantilla del tipo de novedad', max_length=255, verbose_name='template')),
                ('image', models.ImageField(help_text='Imagen del tipo de novedad', null=True, upload_to=core.models.type_new_path, verbose_name='image')),
                ('info', jsonfield.fields.JSONField(default=dict)),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1)),
                ('classification_news', models.ForeignKey(help_text='Clasificación del tipo de novedad', on_delete=django.db.models.deletion.PROTECT, to='core.ClassificationNews', verbose_name='classification_news')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonNews',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.News', verbose_name='news')),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Person', verbose_name='persons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='type_person',
            field=models.ForeignKey(help_text='tipo de persona', on_delete=django.db.models.deletion.PROTECT, to='core.TypePerson', verbose_name='type_person'),
        ),
        migrations.AddField(
            model_name='news',
            name='people',
            field=models.ManyToManyField(related_name='people', through='core.PersonNews', to='core.Person', verbose_name='people'),
        ),
        migrations.AddField(
            model_name='news',
            name='type_news',
            field=models.ForeignKey(help_text='Tipo de la novedad', on_delete=django.db.models.deletion.PROTECT, to='core.TypeNews', verbose_name='type_news'),
        ),
        migrations.AddField(
            model_name='news',
            name='vehicles',
            field=models.ManyToManyField(related_name='vehicles', through='core.VehicleNews', to='core.Vehicle', verbose_name='vehicles'),
        ),
        migrations.AddField(
            model_name='materialnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.News', verbose_name='news'),
        ),
    ]
