# Generated by Django 3.0 on 2021-07-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
