# Generated by Django 3.2.12 on 2025-05-01 16:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_client_type_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIConsumerTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text="Paths permitidos ej: ['/api/zoho/novelties/']", size=None)),
                ('extra_permissions', models.JSONField(blank=True, default=dict)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiconsumer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
            options={
                'unique_together': {('consumer', 'tenant')},
            },
        ),
    ]
