# Generated by Django 3.2.12 on 2025-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconsumer',
            name='has_full_access',
            field=models.BooleanField(default=False),
        ),
    ]
