# Generated by Django 3.2.12 on 2025-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiconsumer_has_full_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconsumer',
            name='last_used_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='apiconsumer',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
