# Generated by Django 3.2.12 on 2025-06-04 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250501_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconsumertenant',
            name='allowed_paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text="Paths permitidos ej: ['/api/api/novelties/']", size=None),
        ),
    ]
