# Generated by Django 3.2.12 on 2025-07-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_client_type_news'),
        ('api', '0004_alter_apiconsumertenant_allowed_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialRecognitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='facialrecognitionevent',
            index=models.Index(fields=['user_id'], name='api_facialr_user_id_8c00c3_idx'),
        ),
        migrations.AddIndex(
            model_name='facialrecognitionevent',
            index=models.Index(fields=['event_time'], name='api_facialr_event_t_753f9a_idx'),
        ),
    ]
