# Generated by Django 3.2.12 on 2025-07-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250709_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacialRecognitionEvent',
        ),
    ]
