# Generated by Django 3.0 on 2021-10-20 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='code')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('ficha', models.CharField(help_text='Ficha para comparar con plataformas externas, Ej: IBARTI', max_length=20, null=True, verbose_name='ficha')),
                ('identification_number', models.CharField(blank=True, max_length=50, verbose_name='identification number')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='address')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='phone')),
                ('security_code', models.CharField(max_length=20, null=True, verbose_name='security_code')),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('type_user', models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('AUDITOR', 'AUDITOR'), ('USER', 'USER'), ('ADMINISTRADOR', 'ADMINISTRADOR')], default='ADMINISTRADOR', help_text='Tipo de usuario. Representa el rol del usuario en el sistema', max_length=50, verbose_name='type user')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('info', jsonfield.fields.JSONField(default=dict)),
                ('is_oesvica', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last password change')),
                ('jwt_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('last_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='last sync date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='LocationUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Location', verbose_name='location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users', through='security.LocationUser', to='main.Location', verbose_name='locations'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_user',
            field=models.ForeignKey(blank=True, help_text='Usuario de seguridad', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='security_user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
