# Generated by Django 3.2.12 on 2022-03-31 14:26

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schema_name',
            field=models.CharField(db_index=True, default='public', max_length=63, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
