# Generated by Django 3.0 on 2021-07-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default=1234, help_text='Código que se usaría para las sincronización con apps externas', max_length=255, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
    ]
