# Generated by Django 3.0 on 2021-07-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20210727_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='code'),
        ),
    ]
