# Generated by Django 3.0 on 2021-08-24 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20210728_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='identification number'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_user',
            field=models.ForeignKey(blank=True, help_text='Usuario de seguridad', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='security_user'),
        ),
    ]
