# Generated by Django 3.0 on 2021-08-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20210823_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_oesvica',
            field=models.BooleanField(default=False),
        ),
    ]
