# Generated by Django 3.0 on 2021-08-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_user_is_oesvica'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ficha',
            field=models.CharField(help_text='Ficha para comparar con plataformas externas, Ej: IBARTI', max_length=20, null=True, verbose_name='ficha'),
        ),
    ]
