# Generated by Django 3.0 on 2021-08-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_news_location'),
        ('security', '0008_auto_20210825_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users', through='security.LocationUser', to='main.Location', verbose_name='locations'),
        ),
    ]
