# Generated by Django 3.0 on 2021-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_auto_20210825_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('AUDITOR', 'AUDITOR'), ('USER', 'USER'), ('ADMINISTRADOR', 'ADMINISTRADOR')], default='ADMINISTRADOR', help_text='Tipo de usuario. Representa el rol del usuario en el sistema', max_length=50, verbose_name='type user'),
        ),
    ]
