# Generated by Django 3.0 on 2021-09-15 16:12

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typenews',
            name='template',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
