# Generated by Django 3.0 on 2021-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typenews',
            name='is_changing_of_the_guard',
            field=models.BooleanField(default=False),
        ),
    ]
