# Generated by Django 3.0 on 2021-09-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210915_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateData',
        ),
    ]
