# Generated by Django 3.0 on 2021-10-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_templatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typenews',
            name='info',
            field=models.CharField(max_length=255),
        ),
    ]
