# Generated by Django 3.0 on 2021-11-16 13:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0002_auto_20211116_0956'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción de la Notificación', max_length=255, unique=True, verbose_name='description')),
                ('type', models.SmallIntegerField(choices=[(0, 'Recurrente'), (1, 'Obligatoria')], default=0, verbose_name='type')),
                ('frequency', models.SmallIntegerField(choices=[(1, 'Todos los días'), (2, 'Solo un día'), (3, 'Mas de un día'), (4, 'días por semana')], default=1, verbose_name='frequency')),
                ('day', models.DateField(blank=True, null=True, verbose_name='day')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None, verbose_name='days')),
                ('week_days', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=7, verbose_name='week days')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(related_name='notifications', through='setting.GroupNotification', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.Notification', verbose_name='notification')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Schedule', verbose_name='schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='schedule',
            field=models.ManyToManyField(related_name='notifications', through='setting.ScheduleNotification', to='main.Schedule', verbose_name='schedule'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TypeNews', verbose_name='type_news'),
        ),
        migrations.AddField(
            model_name='groupnotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.Notification', verbose_name='notification'),
        ),
    ]
