# Generated by Django 3.0 on 2021-07-23 03:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0002_auto_20210722_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción de la Notificación', max_length=255, unique=True, verbose_name='description')),
                ('type', models.SmallIntegerField(choices=[(0, 'Recurrente'), (1, 'Obligatoria')], default=0, verbose_name='type')),
                ('every_day', models.BooleanField(default=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(related_name='notifications', through='setting.GroupNotification', to='auth.Group', verbose_name='groups')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Schedule', verbose_name='schedule')),
                ('type_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TypeNews', verbose_name='type_news')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupnotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.Notification', verbose_name='notification'),
        ),
    ]
