# Generated by Django 3.0 on 2021-08-12 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('day', models.DateField(blank=True, verbose_name='day')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='every_day',
        ),
        migrations.AddField(
            model_name='notification',
            name='frequency',
            field=models.SmallIntegerField(choices=[(1, 'Todos los día'), (2, 'Solo un día'), (3, 'Mas de un día'), (4, 'días por semana')], default=1, verbose_name='frequency'),
        ),
        migrations.AddField(
            model_name='notification',
            name='week_days',
            field=models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='week days'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='notification',
            name='days',
            field=models.ManyToManyField(related_name='notifications_days', to='setting.DaysNotification', verbose_name='days'),
        ),
    ]
