# Generated by Django 3.2.12 on 2022-04-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0017_auto_20220422_1155'),
        ('setting', '0002_auto_20220328_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='periodic_tasks',
            field=models.ManyToManyField(related_name='tasks', to='django_celery_beat.PeriodicTask', verbose_name='periodic tasks'),
        ),
    ]
