# Generated by Django 3.0 on 2021-08-12 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20210812_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='days',
        ),
        migrations.AddField(
            model_name='notification',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=[], size=None),
        ),
        migrations.DeleteModel(
            name='DaysNotification',
        ),
    ]
