# Generated by Django 3.2.12 on 2022-05-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_notification_periodic_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='periodic_tasks',
        ),
    ]
