# Generated by Django 3.0 on 2021-08-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20210812_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='days',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='week_days',
        ),
    ]
