# Generated by Django 3.0 on 2021-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20210812_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='frequency',
            field=models.SmallIntegerField(choices=[(1, 'Todos los días'), (2, 'Solo un día'), (3, 'Mas de un día'), (4, 'días por semana')], default=1, verbose_name='frequency'),
        ),
    ]
