# Generated by Django 3.0 on 2021-08-12 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20210812_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=[], size=None, verbose_name='days'),
        ),
    ]
