# Generated by Django 3.0 on 2021-08-12 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_notification_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None, verbose_name='days'),
        ),
    ]
