# Generated by Django 3.2.12 on 2025-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_notification_periodic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialRecognitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='facialrecognitionevent',
            index=models.Index(fields=['user_id'], name='setting_fac_user_id_db0bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='facialrecognitionevent',
            index=models.Index(fields=['event_time'], name='setting_fac_event_t_ee94bc_idx'),
        ),
    ]
