# Generated by Django 3.0 on 2021-08-12 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20210812_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='week_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=list, size=7, verbose_name='week days'),
        ),
    ]
