# Generated by Django 3.2.12 on 2025-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_auto_20250718_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facialrecognitionevent',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
