# Generated by Django 3.0 on 2021-08-12 18:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_notification_week_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='week_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=7, verbose_name='week days'),
        ),
    ]
