# Generated by Django 3.0 on 2021-08-24 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210823_2035'),
        ('setting', '0009_auto_20210812_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='schedule',
        ),
        migrations.CreateModel(
            name='ScheduleNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.Notification', verbose_name='notification')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Schedule', verbose_name='schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='schedule',
            field=models.ManyToManyField(related_name='notifications', through='setting.ScheduleNotification', to='main.Schedule', verbose_name='schedule'),
        ),
    ]
