# Generated by Django 3.2.12 on 2025-08-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_alter_facialrecognitionevent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='facialrecognitionevent',
            name='user_name',
            field=models.CharField(max_length=255, null=True, verbose_name='user name'),
        ),
    ]
