# Generated by Django 3.0 on 2021-10-20 01:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('phone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone1')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone2')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(help_text='Código del material', max_length=255, unique=True, verbose_name='code')),
                ('serial', models.CharField(help_text='Serial del material', max_length=255, unique=True, verbose_name='serial')),
                ('description', models.CharField(help_text='Descripción del material', max_length=255, unique=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('message', models.TextField(help_text='Mensaje de la novedad', verbose_name='message')),
                ('info', jsonfield.fields.JSONField(default=dict)),
                ('employee', models.CharField(help_text='Ficha del trabajador que generó la novedad', max_length=255, verbose_name='employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(help_text='Código de la persona', max_length=255, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Nombre de la persona', max_length=255, verbose_name='name')),
                ('last_name', models.CharField(help_text='Apellido de la persona', max_length=255, verbose_name='lastname')),
                ('doc_ident', models.CharField(help_text='Documento de Identidad de la persona', max_length=255, unique=True, verbose_name='doc_ident')),
                ('address', models.CharField(help_text='Dirección de la persona', max_length=255, verbose_name='address')),
                ('phone', models.CharField(help_text='Teléfono de la persona', max_length=255, verbose_name='phone')),
                ('mobile', models.CharField(help_text='Número de celular de la persona', max_length=255, verbose_name='mobile')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción del horario', max_length=255, unique=True, verbose_name='description')),
                ('start_time', models.TimeField(blank=True, help_text='Hora Inicial', null=True)),
                ('final_hour', models.TimeField(blank=True, help_text='Hora final', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(help_text='Descripción del Tipo de Persona', max_length=255, unique=True, verbose_name='code')),
                ('priority', models.CharField(help_text='Prioridad del tipo de persona', max_length=255, verbose_name='code')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('license_plate', models.CharField(help_text='Placa del vehiculo', max_length=255, unique=True, verbose_name='license_plate')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.News', verbose_name='news')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Vehicle', verbose_name='vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.News', verbose_name='news')),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Person', verbose_name='persons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='type_person',
            field=models.ForeignKey(help_text='tipo de persona', on_delete=django.db.models.deletion.PROTECT, to='main.TypePerson', verbose_name='type_person'),
        ),
    ]
