# Generated by Django 3.0 on 2021-12-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211116_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_last_name',
            field=models.CharField(help_text='Apellido del propieatario del vehiculo', max_length=255, null=True, unique=True, verbose_name='owner last name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(help_text='Nombre del propieatario del vehiculo', max_length=255, null=True, unique=True, verbose_name='owner name'),
        ),
    ]
