# Generated by Django 3.0 on 2021-10-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211019_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='message',
        ),
    ]
