# Generated by Django 3.0 on 2021-07-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210722_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='materials',
            field=models.ManyToManyField(related_name='news', through='main.MaterialNews', to='main.Material', verbose_name='materials'),
        ),
        migrations.AlterField(
            model_name='news',
            name='people',
            field=models.ManyToManyField(related_name='news', through='main.PersonNews', to='main.Person', verbose_name='people'),
        ),
        migrations.AlterField(
            model_name='news',
            name='vehicles',
            field=models.ManyToManyField(related_name='news', through='main.VehicleNews', to='main.Vehicle', verbose_name='vehicles'),
        ),
    ]
