# Generated by Django 3.0 on 2021-12-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211210_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_last_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_full_name',
            field=models.CharField(help_text='Nombre y Apellido del propieatario del vehiculo', max_length=255, null=True, unique=True, verbose_name='owner full name'),
        ),
    ]
