# Generated by Django 3.0 on 2021-07-23 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210723_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialnews',
            name='material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.Material', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='materialnews',
            name='news',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.News', verbose_name='news'),
        ),
    ]
