# Generated by Django 3.0 on 2021-10-20 17:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='template',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
