# Generated by Django 3.0 on 2021-10-20 17:28

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=apps.main.models.get_new_number, verbose_name='Number'),
        ),
    ]
