# Generated by Django 3.0 on 2021-12-12 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211210_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTools',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('serial', models.CharField(help_text='Serial', max_length=255, unique=True, verbose_name='serial')),
                ('description', models.CharField(help_text='Descripción', max_length=255, null=True, verbose_name='description')),
                ('model', models.CharField(help_text='Modelo', max_length=255, null=True, verbose_name='model')),
                ('color', models.CharField(help_text='Color', max_length=255, null=True, verbose_name='color')),
                ('mark', models.CharField(help_text='Marca', max_length=255, null=True, verbose_name='mark')),
                ('license_plate', models.CharField(help_text='Placa', max_length=255, null=True, verbose_name='license_plate')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
