# Generated by Django 3.0 on 2021-12-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_equipmenttools'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttools',
            name='year',
            field=models.CharField(help_text='Año', max_length=255, null=True, verbose_name='year'),
        ),
    ]
