# Generated by Django 3.0 on 2021-08-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_news_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='final_hour',
            field=models.TimeField(blank=True, help_text='Hora final', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Hora Inicial', null=True),
        ),
    ]
