# Generated by Django 3.2.12 on 2022-03-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_equipmenttools_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeperson',
            name='is_institution',
            field=models.BooleanField(default=False),
        ),
    ]
