# Generated by Django 3.2.12 on 2022-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_typeperson_is_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección de la persona', max_length=255, null=True, verbose_name='address'),
        ),
    ]
