# Generated by Django 3.0 on 2021-08-24 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20210811_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(help_text='Usuario por el que fue crada la novedad', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='doc_ident',
            field=models.CharField(help_text='Documento de Identidad de la persona', max_length=255, unique=True, verbose_name='doc_ident'),
        ),
    ]
