# Generated by Django 3.2.12 on 2025-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeperson',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
