# Generated by Django 3.0 on 2021-08-24 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210823_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('phone1', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone1')),
                ('phone2', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone2')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
