# Generated by Django 3.2.12 on 2025-02-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_typeperson_is_contractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeperson',
            old_name='is_contractor',
            new_name='requires_company_data',
        ),
    ]
