# Generated by Django 3.0 on 2021-08-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.ForeignKey(help_text='Ubicacion o Libro donde se generó la novedad', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Location', verbose_name='location'),
        ),
    ]
