# Generated by Django 3.2.12 on 2025-02-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_is_contractor_typeperson_requires_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='Modelo del vehiculo', max_length=255, null=True, verbose_name='model'),
        ),
    ]
