# Generated by Django 3.2.12 on 2025-02-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeperson',
            name='requires_guide_number',
            field=models.BooleanField(default=False),
        ),
    ]
