# Generated by Django 3.2.12 on 2025-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_typeperson_requires_guide_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=255, verbose_name='code'),
        ),
    ]
