# Generated by Django 3.2.12 on 2025-04-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_location_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='serial',
            field=models.CharField(blank=True, help_text='Serial del material', max_length=255, null=True, verbose_name='serial'),
        ),
    ]
