# Generated by Django 3.2.12 on 2025-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_material_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='person',
            name='rif',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rif'),
        ),
    ]
