# Generated by Django 3.2.12 on 2025-04-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20250421_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, help_text='Número de celular de la persona', max_length=255, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de la persona', max_length=255, null=True, verbose_name='phone'),
        ),
    ]
