# Generated by Django 3.2.12 on 2025-06-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20250421_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='blacklist_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='blacklist reason'),
        ),
    ]
