# Generated by Django 3.2.12 on 2025-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20250604_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='default_visit_location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lugar de visita por defecto'),
        ),
        migrations.AddField(
            model_name='person',
            name='default_visit_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de visita por defecto'),
        ),
    ]
