# Generated by Django 3.2.12 on 2025-06-26 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20250617_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('persons', models.ManyToManyField(blank=True, related_name='access_groups', to='main.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
