# Generated by Django 3.2.12 on 2025-06-26 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_accessgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('access_type', models.CharField(choices=[('single', 'Simple'), ('recurrente', 'Recurrente')], default='single', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('week_days', models.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_entries', to='main.accessgroup')),
                ('persons', models.ManyToManyField(blank=True, related_name='access_entries', to='main.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
