# Generated by Django 3.2.12 on 2025-06-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_accessentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessentry',
            old_name='date',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='accessentry',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
