# Generated by Django 3.2.12 on 2025-06-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20250626_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessentry',
            name='access_type',
            field=models.CharField(choices=[('single', 'Simple'), ('recurrent', 'Recurrente')], default='single', max_length=20),
        ),
    ]
