# Generated by Django 3.2.12 on 2025-07-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_accessentry_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessentry',
            name='specific_days',
            field=models.JSONField(blank=True, help_text='Días específicos del mes (1-31)', null=True),
        ),
    ]
