# Generated by Django 3.2.12 on 2025-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_accessentry_specific_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeperson',
            name='requires_access_verification',
            field=models.BooleanField(default=False),
        ),
    ]
