# Generated by Django 3.2.12 on 2025-07-02 18:27

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_typeperson_requires_access_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessentry',
            name='voucher',
            field=models.ImageField(help_text='Comprobante del acceso', null=True, upload_to=apps.main.models.access_entry_path, verbose_name='voucher'),
        ),
    ]
