# Generated by Django 3.2.12 on 2025-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_accessentry_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2, verbose_name='Sexo'),
        ),
    ]
